### ISSUE TITLE
how to use git lfs pointer file to download file 

### ISSUE THREAD

**Issue by GitHubzhangweizhen** [benedekrozemberczki/datasets#6]

**Comment by benedekrozemberczki** [comment]
Could you provide more details?

**Comment by abidikhairi** [comment]
same issue here, i cant download any of \<dataset\>_target.csv, because they are referenced as lfs pointers.
Scenario:
1. download deezer_europe dataset
2. extract archive
3. put dataset dir in any git project directory
4. try to pull target.csv file using `git lfs pull -I deezer_europe`
5. expect target file to be fetched but nothing happens
Could you provide an example of how to download the datasets.
Thanks.
